# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
notifications:
  on_success: change
  on_failure: always
before_install:
  - brew update
  - brew install xctool
script:
  - xctool -workspace Example/DPLoadingButton.xcworkspace -scheme DPLoadingButton -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
